kiosk_mode:
  entity_settings:
    - entity:
        input_boolean.kiosk: 'on'
      kiosk: true
    - entity:
        input_boolean.kiosk_hide_account: 'on'
      hide_account: true
    - entity:
        input_boolean.kiosk_hide_notifications: 'on'
      hide_notifications: true
    - entity:
        input_boolean.kiosk_hide_header: 'on'
      hide_header: true
    - entity:
        input_boolean.kiosk_hide_menubutton: 'on'
      hide_menubutton: true
    - entity:
        input_boolean.kiosk_hide_sidebar: 'on'
      hide_sidebar: true
    - entity:
        input_boolean.kiosk_hide_search: 'on'
      hide_search: true
    - entity:
        input_boolean.kiosk_hide_assistant: 'on'
      hide_assistant: true
    - entity:
        input_boolean.kiosk_hide_refresh: 'on'
      hide_refresh: true
    - entity:
        input_boolean.kiosk_hide_unused_entities: 'on'
      hide_unused_entities: true
    - entity:
        input_boolean.kiosk_hide_reload_resources: 'on'
      hide_reload_resources: true
    - entity:
        input_boolean.kiosk_hide_edit_dashboard: 'on'
      hide_edit_dashboard: true
    - entity:
        input_boolean.kiosk_hide_overflow: 'on'
      hide_overflow: true
    - entity:
        input_boolean.kiosk_hide_dialog_header_history: 'on'
      hide_dialog_header_history: true
    - entity:
        input_boolean.kiosk_hide_dialog_header_settings: 'on'
      hide_dialog_header_settings: true
    - entity:
        input_boolean.kiosk_hide_dialog_header_overflow: 'on'
      hide_dialog_header_overflow: true
    - entity:
        input_boolean.kiosk_hide_dialog_history: 'on'
      hide_dialog_history: true
    - entity:
        input_boolean.kiosk_hide_dialog_logbook: 'on'
      hide_dialog_logbook: true
    - entity:
        input_boolean.kiosk_hide_dialog_attributes: 'on'
      hide_dialog_attributes: true
    - entity:
        input_boolean.kiosk_hide_dialog_update_actions: 'on'
      hide_dialog_update_actions: true
    - entity:
        input_boolean.kiosk_hide_dialog_timer_actions: 'on'
      hide_dialog_timer_actions: true
    - entity:
        input_boolean.kiosk_hide_dialog_history_show_more: 'on'
      hide_dialog_history_show_more: true
    - entity:
        input_boolean.kiosk_hide_dialog_logbook_show_more: 'on'
      hide_dialog_logbook_show_more: true
    - entity:
        input_boolean.kiosk_block_overflow: 'on'
      block_overflow: true
    - entity:
        input_boolean.kiosk_block_mouse: 'on'
      block_mouse: true
title: Kiosk-mode Overview
views:
  - theme: Backend-selected
    title: Kiosk-mode overview
    path: kiosk-mode-overview
    badges: []
    cards:
      - type: entities
        title: Kiosk settings
        entities:
          - type: section
            label: General options
          - entity: input_boolean.kiosk
          - entity: input_boolean.kiosk_hide_account
          - entity: input_boolean.kiosk_hide_notifications
          - entity: input_boolean.kiosk_hide_header
          - entity: input_boolean.kiosk_hide_menubutton
          - entity: input_boolean.kiosk_hide_sidebar
          - entity: input_boolean.kiosk_hide_search
          - entity: input_boolean.kiosk_hide_assistant
          - entity: input_boolean.kiosk_hide_overflow
          - entity: input_boolean.kiosk_hide_refresh
          - entity: input_boolean.kiosk_hide_unused_entities
          - entity: input_boolean.kiosk_hide_reload_resources
          - entity: input_boolean.kiosk_hide_edit_dashboard
          - entity: input_boolean.kiosk_block_overflow
          - entity: input_boolean.kiosk_block_mouse
          - type: section
            label: More-info dialogs options
          - entity: sun.sun
          - entity: zone.home
          - entity: timer.laundry
          - entity: input_boolean.kiosk_hide_dialog_header_history
          - entity: input_boolean.kiosk_hide_dialog_header_settings
          - entity: input_boolean.kiosk_hide_dialog_header_overflow
          - entity: input_boolean.kiosk_hide_dialog_history
          - entity: input_boolean.kiosk_hide_dialog_logbook
          - entity: input_boolean.kiosk_hide_dialog_attributes
          - entity: input_boolean.kiosk_hide_dialog_update_actions
          - entity: input_boolean.kiosk_hide_dialog_timer_actions
          - entity: input_boolean.kiosk_hide_dialog_history_show_more
          - entity: input_boolean.kiosk_hide_dialog_logbook_show_more
